name: ASP.NET Core CI

on: 
  push: 
      branches: [ "develop" ]    
  pull_request:
      branches: [ "develop" ]



jobs:
  build: 
    runs-on: [self-hosted, Windows, X64]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies 
      run: dotnet restore 

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish
      run: dotnet publish --configuration Release --no-build -o ./publish

    - name: Stop running app (if exists)
      run: |
        taskkill /F /IM github-practice.exe 
      continue-on-error: true

    - name: Start app
      run: |
        cd C:\inetpub\wwwroot\github-actions
        start github-practice.exe
      shell: powershell

    - name: Restart IIS
      run: iisreset
      shell: powershell